name: CI

on:
  pull_request:
    branches: [master, feature/*]
    types: [opened, edited, reopened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
