name: Docs

on:
  pull_request:
    branches: [master]
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [master]

jobs:
  docs_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Build Packages
        run: |
          yarn --frozen-lockfile
          yarn build

      - name: Deploy to Now (Dev)
        if: github.event_name == 'pull_request'
        run: npx vercel ./apps/docs --confirm --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Now (Prod)
        if: github.event_name == 'push'
        run: npx vercel ./apps/docs --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
