name: Publish

on:
  push:
    branches: [master]

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "http://registry.npmjs.org"

      - name: Publish
        run: |
          npm i -g yarn
          yarn
          yarn config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # gpr_publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: "13.x"
  #         registry-url: "https://npm.pkg.github.com"

  #     - name: Publish
  #       run: |
  #         npm i -g yarn
  #         yarn
  #         yarn publish-packages
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
