name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Publish to NPM & GPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
