name: Storybook Dev

on:
  pull_request:
    branches: [master]
    types: [opened, edited, reopened, synchronize]
  # push:
  #   branches: [master]

jobs:
  storybook_dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Build Packages
        run: |
          yarn
          yarn build

      - name: Storybook Build
        run: |
          yarn lerna bootstrap
          yarn storybook:build

      - name: Deploy to Now
        run: npx now ./hooky-storybook --token ${{ secrets.NOW_TOKEN }} --confirm
