name: Storybook

on:
  pull_request:
    branches: [master]
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [master]

jobs:
  storybook_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Build Packages
        run: |
          yarn
          yarn build

      - name: Storybook Build
        run: |
          yarn lerna bootstrap
          yarn storybook:build

      - name: Deploy to Now (Dev)
        if: github.event_name == 'pull_request'
        run: npx vercel ./hooky-storybook --confirm --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Now (Prod)
        if: github.event_name == 'push'
        run: npx vercel ./hooky-storybook --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
