name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: Build & Test
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - run: yarn lerna bootstrap
      - run: yarn test
